version: "3.8"

services:
  mongodb:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  api:
    build: .
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/blog
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_ENVIRONMENT: ${PINECONE_ENVIRONMENT}
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
