version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: blog
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: nestjs-api
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/blog
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_ENVIRONMENT: ${PINECONE_ENVIRONMENT}
    restart: unless-stopped
    deploy:
      replicas: 2  # For scalability (run `docker compose up --scale api=2`)
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  mongo_data: