version: "3.8"

services:
  api:
    build: .
    restart: unless-stopped
    depends_on:
      - mongodb  # optional
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/blog
    networks:
      - shared-backend

networks:
  shared-backend:
    external: true
