version: "3.8"

services:
  shared-mongodb:
    image: mongo:6.0
    container_name: shared-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - shared-backend
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  post-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-api-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: mongodb://shared-mongodb:27017/posts
      WS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_ENVIRONMENT: ${PINECONE_ENVIRONMENT}
      PORT: 3001
      HOST: 0.0.0.0
    depends_on:
      - shared-mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - shared-backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    entrypoint: ["./wait-for-mongo.sh", "npm", "start"]  # see below for wait-for-mongo.sh script

networks:
  shared-backend:
    external: true
